export const siteConfig = {
  name: "Car Edits",
  legalName: "Car Edits",
  tagline: "Capture Every Drive. Create Every Story.",
  description:
    "Premium Automotive Photography & Cinematic Video Production. Car & bike delivery shoots, vehicle launch events, drone films and corporate coverage. Starts from ₹3,999. Based in Kolkata, serving PAN India.",
  url: "https://careditskolkata.com",
  startingPrice: 3999,
  location: "Kolkata, West Bengal",
  serviceArea: "PAN India",
  phone: "+91 90000 00000",
  phoneRaw: "919000000000",
  whatsapp: "919000000000",
  email: "hello@careditskolkata.com",
  address: "Kolkata, West Bengal, India",
  social: {
    instagram: "https://instagram.com/careditskolkata",
    facebook: "https://facebook.com/careditskolkata",
    youtube: "https://youtube.com/@careditskolkata",
    linkedin: "https://linkedin.com/company/careditskolkata",
  },
  nav: [
    { label: "Home", href: "/" },
    { label: "About", href: "/about" },
    { label: "Services", href: "/services" },
    { label: "Portfolio", href: "/portfolio" },
    { label: "Pricing", href: "/pricing" },
    { label: "Gallery", href: "/gallery" },
    { label: "Reviews", href: "/reviews" },
    { label: "Blog", href: "/blog" },
    { label: "Contact", href: "/contact" },
  ],
  footerLinks: {
    company: [
      { label: "About Us", href: "/about" },
      { label: "Portfolio", href: "/portfolio" },
      { label: "Reviews", href: "/reviews" },
      { label: "Blog", href: "/blog" },
      { label: "Contact", href: "/contact" },
    ],
    services: [
      { label: "Car Delivery Shoot", href: "/services/car-delivery-shoot" },
      { label: "Bike Delivery Shoot", href: "/services/bike-delivery-shoot" },
      { label: "Vehicle Launch Event", href: "/services/vehicle-launch-event" },
      { label: "Drone Shoot", href: "/services/drone-shoot" },
      { label: "Corporate Event", href: "/services/corporate-event" },
      { label: "All Services", href: "/services" },
    ],
    legal: [
      { label: "Privacy Policy", href: "/privacy-policy" },
      { label: "Terms & Conditions", href: "/terms" },
      { label: "Refund Policy", href: "/refund-policy" },
      { label: "Cancellation Policy", href: "/cancellation-policy" },
    ],
  },
} as const;
